version: "3.9"

networks:
  traefik-net:
    external: true

services:
  dashboard:
    image: "${DASHBOARD_IMAGE}"
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`admin.paytic.io`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"
    networks:
      - traefik-net
    deploy:
      restart_policy:
        condition: any
